Asynchronous communication
miwashun/chat-space pull request #9
Opened 2019-02-18 08:52 UTC by miwashun

非同期通信を導入しました
プルリクエストよろしくお願いします

2019-02-18 08:59 UTC, yusukeyamane commented on app/controllers/messages_controller.rb
> +        format.html { redirect_to group_messages_path(@group) , notice: 'メッセージが送信されました'}
動画を見た所非同期の場合はフラッシュメッセージが出ないという実装になっているので、手元では同期的な処理になっている気がします。

この行を消しても問題なく動作するかご確認頂けますか？

2019-02-19 02:00 UTC, miwashun commented on app/controllers/messages_controller.rb
> +        format.html { redirect_to group_messages_path(@group) , notice: 'メッセージが送信されました'}
非同期通信できていなかったので非同期通信を設定しました

2019-02-19 02:55 UTC, hirozak commented on app/assets/javascripts/message.js
> +                   ${message.content}
画像の表示がないと思うので追加しましょう

2019-02-19 02:55 UTC, hirozak commented on app/assets/javascripts/message.js
> +                  </p>
子要素がありませんがこのタグは必要なんですか？

2019-02-19 02:55 UTC, hirozak commented on app/assets/javascripts/message.js
> +    var html = `<div class="message" data-message_id>
data属性の指定ができていないかと思います

2019-02-19 03:03 UTC, miwashun commented on app/assets/javascripts/message.js
> +                  </p>
とりあえず消しました

2019-02-19 03:27 UTC, miwashun commented on app/assets/javascripts/message.js
> +                  </p>
この行を消すと書式が崩れました

2019-02-19 09:57 UTC, miwashun commented on app/assets/javascripts/message.js
> +                  </p>
pタグからdivタグに変えcontentとimgタグをネストしました

2019-02-19 09:58 UTC, miwashun commented on app/assets/javascripts/message.js
> +                   ${message.content}
画像を非同期通信できました

2019-02-19 10:20 UTC, miwashun commented on app/assets/javascripts/message.js
> +    var html = `<div class="message" data-message_id>
data属性を調べた結果今は必要なさそうなので削除しました

2019-02-19 13:04 UTC, ReoKuriyama requested changes
rspecのファイルが混ざっていますね 👀 
このPRに混ざらないようにしましょう
ただし、今は技術的に難しいと思うので次回から気をつけましょう

2019-02-19 13:04 UTC, ReoKuriyama commented on app/assets/javascripts/message.js
> +
空行消しましょう

2019-02-19 13:04 UTC, ReoKuriyama commented on app/controllers/messages_controller.rb
> +        format.html { redirect_to group_messages_path(@group) , notice: 'メッセージが送信されました'}
html形式でレスポンスを返さないので消してしまいましょう

2019-02-20 00:45 UTC, miwashun commented on app/assets/javascripts/message.js
> +
消しました

2019-02-20 00:47 UTC, miwashun commented on app/controllers/messages_controller.rb
> +        format.html { redirect_to group_messages_path(@group) , notice: 'メッセージが送信されました'}
削除しました

2019-02-20 02:09 UTC, hirozak commented
プッシュしてください

2019-02-20 03:01 UTC, TOMARUMARU commented on app/assets/javascripts/message.js
> +      $('.form__message').val('')
reset使いましょう

2019-02-20 04:17 UTC, miwashun commented on app/assets/javascripts/message.js
> +      $('.form__message').val('')
$('.form__message'.val('')を消して$("#create_message")[0].reset();だけにしました

2019-02-20 05:05 UTC, TOMARUMARU approved these changes
LGTM

2019-02-20 05:15 UTC, merged